/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "aether_constants.h"



const aetherConstants g_aether_constants;

aetherConstants::aetherConstants() {
}



