/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef aether_CONSTANTS_H
#define aether_CONSTANTS_H

#include "aether_types.h"



class aetherConstants {
 public:
  aetherConstants();

};

extern const aetherConstants g_aether_constants;



#endif
