/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef aether_TYPES_H
#define aether_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




typedef struct _ServiceUnavailable__isset {
  _ServiceUnavailable__isset() : error_code(false), error_message(false) {}
  bool error_code;
  bool error_message;
} _ServiceUnavailable__isset;

class ServiceUnavailable : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  ServiceUnavailable() : error_code(0), error_message() {
  }

  virtual ~ServiceUnavailable() throw() {}

  int32_t error_code;
  std::string error_message;

  _ServiceUnavailable__isset __isset;

  void __set_error_code(const int32_t val) {
    error_code = val;
  }

  void __set_error_message(const std::string& val) {
    error_message = val;
  }

  bool operator == (const ServiceUnavailable & rhs) const
  {
    if (!(error_code == rhs.error_code))
      return false;
    if (!(error_message == rhs.error_message))
      return false;
    return true;
  }
  bool operator != (const ServiceUnavailable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServiceUnavailable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(ServiceUnavailable &a, ServiceUnavailable &b);

typedef struct _MoxelRepresentation__isset {
  _MoxelRepresentation__isset() : x(false), y(false), z(false) {}
  bool x;
  bool y;
  bool z;
} _MoxelRepresentation__isset;

class MoxelRepresentation {
 public:

  static const char* ascii_fingerprint; // = "EFFAD640FBA2CA56C50155B2A4545897";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xFA,0xD6,0x40,0xFB,0xA2,0xCA,0x56,0xC5,0x01,0x55,0xB2,0xA4,0x54,0x58,0x97};

  MoxelRepresentation() : x(0), y(0), z(0) {
  }

  virtual ~MoxelRepresentation() throw() {}

  double x;
  double y;
  double z;

  _MoxelRepresentation__isset __isset;

  void __set_x(const double val) {
    x = val;
  }

  void __set_y(const double val) {
    y = val;
  }

  void __set_z(const double val) {
    z = val;
  }

  bool operator == (const MoxelRepresentation & rhs) const
  {
    if (!(x == rhs.x))
      return false;
    if (!(y == rhs.y))
      return false;
    if (!(z == rhs.z))
      return false;
    return true;
  }
  bool operator != (const MoxelRepresentation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MoxelRepresentation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(MoxelRepresentation &a, MoxelRepresentation &b);

typedef struct _MoxelSpace__isset {
  _MoxelSpace__isset() : moxels(false) {}
  bool moxels;
} _MoxelSpace__isset;

class MoxelSpace {
 public:

  static const char* ascii_fingerprint; // = "CA3A04F6586943FB009547C6AECE5B89";
  static const uint8_t binary_fingerprint[16]; // = {0xCA,0x3A,0x04,0xF6,0x58,0x69,0x43,0xFB,0x00,0x95,0x47,0xC6,0xAE,0xCE,0x5B,0x89};

  MoxelSpace() {
  }

  virtual ~MoxelSpace() throw() {}

  std::vector<MoxelRepresentation>  moxels;

  _MoxelSpace__isset __isset;

  void __set_moxels(const std::vector<MoxelRepresentation> & val) {
    moxels = val;
  }

  bool operator == (const MoxelSpace & rhs) const
  {
    if (!(moxels == rhs.moxels))
      return false;
    return true;
  }
  bool operator != (const MoxelSpace &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MoxelSpace & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(MoxelSpace &a, MoxelSpace &b);



#endif
