//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

Aether_get_moxel_snapshot_args = function(args) {
};
Aether_get_moxel_snapshot_args.prototype = {};
Aether_get_moxel_snapshot_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Aether_get_moxel_snapshot_args.prototype.write = function(output) {
  output.writeStructBegin('Aether_get_moxel_snapshot_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Aether_get_moxel_snapshot_result = function(args) {
  this.success = null;
  this.sunav = null;
  if (args instanceof ServiceUnavailable) {
    this.sunav = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.sunav !== undefined) {
      this.sunav = args.sunav;
    }
  }
};
Aether_get_moxel_snapshot_result.prototype = {};
Aether_get_moxel_snapshot_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new MoxelSpace();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.sunav = new ServiceUnavailable();
        this.sunav.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Aether_get_moxel_snapshot_result.prototype.write = function(output) {
  output.writeStructBegin('Aether_get_moxel_snapshot_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.sunav !== null && this.sunav !== undefined) {
    output.writeFieldBegin('sunav', Thrift.Type.STRUCT, 1);
    this.sunav.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AetherClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
AetherClient.prototype = {};
AetherClient.prototype.get_moxel_snapshot = function() {
  this.send_get_moxel_snapshot();
  return this.recv_get_moxel_snapshot();
};

AetherClient.prototype.send_get_moxel_snapshot = function() {
  this.output.writeMessageBegin('get_moxel_snapshot', Thrift.MessageType.CALL, this.seqid);
  var args = new Aether_get_moxel_snapshot_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

AetherClient.prototype.recv_get_moxel_snapshot = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new Aether_get_moxel_snapshot_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.sunav) {
    throw result.sunav;
  }
  if (null !== result.success) {
    return result.success;
  }
  throw 'get_moxel_snapshot failed: unknown result';
};
